### ISSUE TITLE
Getting error when trying to convert your sample file.

### ISSUE THREAD

**Issue by barulopez** [rogermolas/csv-localizer#8]
Getting the following error when trying to convert your sample file.

```Validating source path ...


Valid source path, finding csv file ...


Validating target path ...


Valid target path, generating output directory ...


Using output directory: project/output




Platform : ios
Generated output directory: project/output
Traceback (most recent call last):
  File "/usr/local/bin/csv-localizer", line 271, in <module>
    main(args, loglevel)
  File "/usr/local/bin/csv-localizer", line 64, in main
    generate_keys(IN_PATH, OUTPUT_DIR, PLATFORM)
  File "/usr/local/bin/csv-localizer", line 115, in generate_keys
    start_localize_ios(source_path, allwrites, LANG_KEYS)
UnboundLocalError: local variable 'LANG_KEYS' referenced before assignment```

**Comment by rogermolas** [comment]
@barulopez `-i` input path is the **directory path** in where the `.csv` file located as I stated here https://github.com/rogermolas/csv-localizer#usage

instead of this
   **`csv-localizer -p ios -i  ~/project/sample.csv -o ~/project`**
   use this
   **`csv-localizer -p ios -i .  -o ~/project`** 
   or 
   **`csv-localizer -p ios -i ~/project/csv_folder  -o ~/project`**

use the directory path of csv files and don't include the .csv file itself, 
this CLI converts multiple csv files that's why it uses the directory as the input source
